# -*- coding: utf-8 -*-
"""shaochen cui_lab12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U0ZRnGldXP10WFwpvec7Cl42l0aSxiP-
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st
import pandas as pd
import streamlit as st
st.write("hello world")

import pandas as pd
import streamlit as st

# Load the CSV file into a pandas DataFrame
df = pd.read_csv('car_data.csv')

# Create sidebar filters for user input
car_name = st.sidebar.text_input('Car_Name')
transmission_type = st.sidebar.multiselect('Transmission', ['Manual', 'Automatic'], default=['Manual', 'Automatic'])
selling_price_range = st.sidebar.slider('Selling_Price', 0, 20, (0, 20))
year_range = st.sidebar.slider('Year', 2000, 2024, (2000, 2024))
submit = st.sidebar.button('Submit')

# Filter the DataFrame based on user inputs upon clicking the Submit button
if submit:
    if car_name:
        df = df[df['Car_Name'].str.contains(car_name, case=False)]
    if transmission_type:
        df = df[df['Transmission'].isin(transmission_type)]
    df = df[df['Selling_Price'].between(*selling_price_range)]
    df = df[df['Year'].between(*year_range)]

# Display the filtered DataFrame in the Streamlit app
st.write(df)

